# Generated by Django 4.0.2 on 2022-02-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages_l_h', models.IntegerField(max_length=9999)),
                ('update_time_p_l_h', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
