# Generated by Django 4.0.2 on 2022-02-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_data',
            name='packages_l_h',
            field=models.IntegerField(),
        ),
    ]
